feat: Use node-fetch in place of isomorphic-fetch
We found that when compiled with webpack, isomorphic-fetch would cause
issues like :
"TypeError: realFetch.call is not a function"

This issue was fixed in connectors with konnectors/libs#724

Since, isomorphic-fetch is only used in node context, the isomorphic
part of this package is not
needed and we can use node-fetch directly, which does not cause the same
issue.

To be able to install node-fetch, I also had to upgrade
all babel related dependencies